name: deforestation
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rasterio
  - rioxarray
  - scipy
  - odc-stac
  - planetary-computer
  - shapely
  - contextily
  - geopandas
  - ipykernel
  - jupyterlab
  - folium
  - matplotlib
  - pystac-client

